---

- name: This playbook is for Ubuntu so far
  debug: msg="Please be aware of some Ubuntu specific code in the playbook. Only Ubuntu is fully supported so far"
  when: ansible_distribution != 'Ubuntu'
  
- name: Create folder for binary
  file: path="{{ btsync_dist  }}" recurse=yes
        owner=root group=root mode=0755
        state=directory

- name: Read BTSync version
  shell: "{{ btsync_dist }}/btsync --help | awk '/^BitTorrent/ { print $3 }'"
  register: btsync_version
  changed_when: false

- name: Download btsync tarball
  get_url: url="{{ btsync_url[ansible_architecture] }}"
           dest=/var/tmp/btsync.tgz force=yes
  register: tarball_downloaded
  when: btsync_version.stdout != btsync_current
           
- name: Unzip btsync binary
  shell: tar xz -C "{{ btsync_dist }}" -f /var/tmp/btsync.tgz btsync
  when: btsync_version.stdout != btsync_current
  notify:
    - restart btsync

- name: Create user 
  user: name="{{ btsync_user }}"
        shell="{{ btsync_shell }}"
        state=present
        system=no

- name: Create btsync working folder 
  file: path="{{ item }}"
        owner="{{ btsync_user }}" group="{{ btsync_user }}" mode=0750
        state=directory
  with_items:
    - "{{ btsync_settings.storage_path }}"
 
- name: Create btsync shares 
  file: path="{{ item.dir }}" recurse=yes
        owner="{{ btsync_user }}" group="{{ btsync_user }}" mode=0750
        state=directory
  with_items:
    - "{{ btsync_settings.shared_folders }}"
  when: item is defined and item.dir
    
- name: Template btsync configuration file
  template: src=btsync.conf.j2
            dest="{{ btsync_conf }}"
            owner="{{ btsync_user }}" group="{{ btsync_user }}" mode=0640
            backup=yes 
  notify:
    - restart btsync

- name: Template upstart configuration
  template: src=upstart.j2
            dest=/etc/init/btsync.conf
            owner=root group=root mode=0640 backup=yes 
  when: ansible_distribution == 'Ubuntu'
  notify:
    - restart btsync

- name: Template BTSync profile for ufw
  template: src=ufw.j2
            dest=/etc/ufw/applications.d/btsync
            owner=root group=root mode=0640
            backup=yes 
  notify:
    - reload ufw

- name: Configure firewall for BTSync
  ufw: rule=allow name='BTSync'
  notify:
    - reload ufw
  
- name: Create firewall rules
  ufw: rule=allow name=BTSync
  when: ansible_distribution == 'Ubuntu'

- name: Encure btsync service is up and running 
  service: name=btsync state=started
