---

- name: This playbook is for Ubuntu only so far
  fail: msg="this is Ubuntu only sorry"
  when: ansible_distribution != 'Ubuntu'
  
- name: Create folder for binary
  file: path="{{ btsync_dist  }}" recurse=yes
        owner=root group=root mode=0755
        state=directory

- name: Download btsync tarball
  get_url: url="{{ btsync_url[ansible_architecture] }}"
           dest=/var/tmp/btsync.tgz
  register: tarball_downloaded
           
- name: Unzip btsync binary
  shell: tar xz -C "{{ btsync_dist }}" -f /var/tmp/btsync.tgz btsync
  when: tarball_downloaded|changed

- name: Create user 
  user: name="{{ btsync_user }}"
        shell="{{ btsync_shell }}"
        state=present
        system=no
 
- name: Create storage folder and shares 
  file: path="{{ item.dir }}" recurse=yes
        owner="{{ btsync_user }}" group="{{ btsync_user }}" mode=0750
        state=directory
  with_items:
    - { dir: "{{ btsync_settings.storage_path }}" }
    - ${btsync_settings.shared_folders}
  when: item is defined and item.dir
    
- name: Template btsync configuration file
  template: src=btsync.conf.j2
            dest="{{ btsync_conf }}"
            owner="{{ btsync_user }}" group="{{ btsync_user }}" mode=0640
            backup=yes 
  notify:
    - restart btsync

- name: Template upstart configuration
  template: src=upstart.j2
            dest=/etc/init/btsync.conf
            owner=root group=root mode=0640 backup=yes 
  notify:
    - restart btsync

- name: Get UFW status output
  shell: ufw status 
  register: ufw_status

  
- name: Is firewall enabled
  shell: /bin/true
  register: ufw_is_enabled
  when: 'ufw_status.stdout_lines[0] == "Status: active" and and ${btsync_settings.listening_port} != 0' 

- name: Template ufw configuration
  template: src=ufw.j2
            dest=/etc/ufw/applications.d/btsync
            owner=root group=root mode=0640
            backup=yes 
  when: ufw_is_enabled|changed
  notify:
    - reload ufw

- name: Configure firewall
  command: ufw allow 'BTSync' 
  when: ufw_is_enabled|changed
  notify:
    - reload ufw
  
- name: Check for btsync process
  command: pgrep -fc btsync
  ignore_errors: yes
  register: pgrep

- name: Start btsync 
  command: "start btsync"
  when: pgrep.rc == 1

- name: Encure btsync service is up and running 
  service: name=btsync state=started
